"""auto update

Revision ID: 594b9d685f1e
Revises: 2c4acc992f21
Create Date: 2026-03-20 09:05:57.542732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594b9d685f1e'
down_revision: Union[str, Sequence[str], None] = '2c4acc992f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('viewer_ip', sa.String(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_views_id'), 'product_views', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_views_id'), table_name='product_views')
    op.drop_table('product_views')
    # ### end Alembic commands ###