"""auto update

Revision ID: 65902c70b0c9
Revises: 837e57c54d65
Create Date: 2026-03-22 21:32:21.993366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65902c70b0c9'
down_revision: Union[str, Sequence[str], None] = '837e57c54d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_histories_id'), 'search_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_histories_id'), table_name='search_histories')
    op.drop_table('search_histories')
    # ### end Alembic commands ###