"""auto update

Revision ID: 837e57c54d65
Revises: 3f6515ab1fb9
Create Date: 2026-03-22 19:42:16.667603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837e57c54d65'
down_revision: Union[str, Sequence[str], None] = '3f6515ab1fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('stripe_session_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'stripe_session_id')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###