"""auto update

Revision ID: dad31124d078
Revises: f14f06009cc0
Create Date: 2026-03-25 15:20:25.603212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad31124d078'
down_revision: Union[str, Sequence[str], None] = 'f14f06009cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'bank_account_holder')
    op.drop_column('vendors', 'bank_iban')
    op.drop_column('vendors', 'bank_verified')
    op.drop_column('vendors', 'bank_name')
    op.drop_column('vendors', 'email')
    op.drop_column('vendors', 'mobile_number')
    op.drop_column('vendors', 'bank_account_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('bank_account_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('bank_verified', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('bank_iban', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vendors', sa.Column('bank_account_holder', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###